service: demo-apollo-server-lambda
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
functions:
  graphql:
    handler: src/server.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 3000
  webpack:
    includeModules: true
  
  dotenv:
    path: dotenv/.env
    logging: false
  